"""Feature engineering for daily UK electricity demand.

Reproduces, in tested and reusable form, the transformations originally written
across the ``03/06/07/08`` notebooks. The conventions here are validated against
``data/processed/energy_features_v3.parquet`` so that features generated by this
module are byte-compatible with what the production model was trained on.

Convention notes
----------------
* Lag features use a plain ``shift`` (strictly past values).
* Rolling statistics are computed *inclusive of the current row*
  (``series.rolling(window)``), matching the training data. This means the
  rolling features peek at the current target during backtests — a mild leakage
  baked into the original pipeline. It is reproduced here for fidelity; see the
  project README's "Future Improvements" for the leakage-free alternative.
"""

from __future__ import annotations

import pandas as pd

from src.config import DATE_COLUMN, TARGET_COLUMN

LAGS = (1, 7, 30)
ROLLING_WINDOWS = (7, 30)


def add_lag_features(df: pd.DataFrame, target: str = TARGET_COLUMN) -> pd.DataFrame:
    """Add ``lag_{1,7,30}`` columns from the target series."""
    df = df.copy()
    for lag in LAGS:
        df[f"lag_{lag}"] = df[target].shift(lag)
    return df


def add_rolling_features(df: pd.DataFrame, target: str = TARGET_COLUMN) -> pd.DataFrame:
    """Add rolling mean/std columns (current-row-inclusive window)."""
    df = df.copy()
    for window in ROLLING_WINDOWS:
        df[f"rolling_mean_{window}"] = df[target].rolling(window).mean()
        df[f"rolling_std_{window}"] = df[target].rolling(window).std()
    return df


def add_calendar_features(df: pd.DataFrame, date_col: str = DATE_COLUMN) -> pd.DataFrame:
    """Add calendar features derived from the settlement date."""
    df = df.copy()
    dates = pd.to_datetime(df[date_col])
    df["year"] = dates.dt.year
    df["month"] = dates.dt.month
    df["quarter"] = dates.dt.quarter
    df["day_of_week"] = dates.dt.dayofweek
    df["day_of_year"] = dates.dt.dayofyear
    df["is_weekend"] = (dates.dt.dayofweek >= 5).astype(int)
    return df


def add_weather_lags(df: pd.DataFrame) -> pd.DataFrame:
    """Add one-day lags of the core weather drivers, when present."""
    df = df.copy()
    weather_lag_map = {
        "temperature_mean": "temp_lag_1",
        "rainfall": "rainfall_lag_1",
        "wind_speed": "wind_lag_1",
    }
    for source, lag_col in weather_lag_map.items():
        if source in df.columns:
            df[lag_col] = df[source].shift(1)
    return df


def build_features(
    df: pd.DataFrame,
    target: str = TARGET_COLUMN,
    date_col: str = DATE_COLUMN,
) -> pd.DataFrame:
    """Run the full feature pipeline on a date-sorted daily demand frame.

    The input must contain at least the date and target columns; weather and
    renewable columns are passed through and used for lags when available.
    """
    df = df.sort_values(date_col).reset_index(drop=True)
    df = add_lag_features(df, target=target)
    df = add_rolling_features(df, target=target)
    df = add_calendar_features(df, date_col=date_col)
    df = add_weather_lags(df)
    return df
